apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: spring.datasource.url
              value: "jdbc:postgresql://10.152.183.61:5432/testdb"
            - name: spring.datasource.usernam
              value: "postgres"
            - name: spring.datasource.password
              value: "123456"    	
